events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # API route for order-service
        location /api/order/ {
            proxy_pass http://localhost:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # API route for products-service
        location /api/product/ {
            proxy_pass http://localhost:8081/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
